import os


# Core behavior
USE_1H_FILTER = True
ALERT_ONLY_NEW = True
ALLOW_EARLY_TREND = True
USE_4H_BREAKOUT_FILTER = True

# Exchange settings
EXCHANGE_ID = "binance"
PRIMARY_EXCHANGE_ID = "binance"
FALLBACK_EXCHANGE_IDS = ("binanceus",)
QUOTE_ASSET = "USDC"
LEVERAGED_TOKENS = ("UP", "DOWN", "BULL", "BEAR")

# Candle limits
DAILY_LIMIT = 260
H4_LIMIT = 120
H1_LIMIT = 120

# Indicator params
EMA_FAST = 10
EMA_MID = 50
EMA_SLOW = 200
EMA_SLOPE_LOOKBACK = 10
EMA_MID_SLOPE_LOOKBACK = 5
MIN_EMA10_SLOPE_PCT = 0.05

MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
MIN_MACD_SPREAD_RATIO = 0.01

RSI_PERIOD = 14
RSI_MIN = 52
RSI_MAX = 75
VOLUME_SMA_PERIOD = 20
VOLUME_RATIO_THRESHOLD = 1.2
BREAKOUT_LOOKBACK_4H = 20

# Retry / rate-limit handling
MAX_RETRIES = 4
INITIAL_RETRY_DELAY = 1.5

# Telegram env variables
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

# State files
LAST_ALERTS_PATH = "last_alerts.json"
CONFIG_STATE_PATH = "config_state.json"
